import Main from "@/components/main";
import Nav from "@/components/nav";
import "@/styles/globals.css";
import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Main>
          <Nav>
            <ul>
              <li>
                <Link href="/home">Home</Link>
              </li>
              <li>
                <Link href="/profile">Profile</Link>
              </li>
              <li>
                <Link href="/">Log out</Link>
              </li>
            </ul>
          </Nav>
          {children}
          <Nav />
        </Main>
      </body>
    </html>
  );
}
